In [ ]:
import pandas as pd
import numpy as np
import re
import emoji

In [ ]:
# LOAD DATA
data = pd.read_csv(r"C:\Users\PC\ScraperTwitter\data\tweets.csv")
data

,tweet_id,date,username,text,likes,retweets,replies,keyword,lang
0,2.040570e+18,Sat Apr 04 23:08:49 +0000 2026,shrimpingbae,sumpah kalo sampe itu anggota TNI ga dikasih s...,0,0,0,mati aja lo,in
1,2.041010e+18,Mon Apr 06 04:20:32 +0000 2026,xeyobog202,Gada tuh cerita pamer-pamer kekayaan di sini. ...,0,0,0,mati aja lo,in
2,2.041160e+18,Mon Apr 06 14:24:28 +0000 2026,LusyBule88,@tham878 Emaklo goblok idiot..termul...mati aj...,0,0,0,mati aja lo,in
3,2.040650e+18,Sun Apr 05 04:47:42 +0000 2026,DhiekaSetyawan,"@phamsaurus @AmirahWahdi Lah ada yg jawabin, g...",0,0,0,mati aja lo,in
4,2.039540e+18,Thu Apr 02 03:04:33 +0000 2026,sleepycatzzz_,Gimanapun baiknya lo kalau orang emang ga sene...,0,0,0,mati aja lo,in
...,...,...,...,...,...,...,...,...,...
27628,2.053630e+18,Mon May 11 00:11:39 +0000 2026,ihanmujaer,aku... gemeter... plis... cantik... banget... ...,0,0,0,lgbt penyakit,in
27629,2.053520e+18,Sun May 10 16:54:30 +0000 2026,ladanghoki,🔞 pokoknya nentto wlw menghadapi hari senin ht...,15,3,1,lgbt penyakit,in
27630,2.051660e+18,Tue May 05 13:43:00 +0000 2026,paakminju,ᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ...,0,0,0,lgbt penyakit,in
27631,2.051660e+18,Tue May 05 13:42:40 +0000 2026,paakminju,ᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ...,1,1,0,lgbt penyakit,in
27632,2.053630e+18,Mon May 11 00:01:06 +0000 2026,KentaKanataa,BENTAR LG TAHUN AJARAN BARU AJDNDNCNCNFJJF,1,0,0,lgbt penyakit,NaN

In [ ]:
#FILTERING ONLY INDONESIAN TEXTS

data = data[data['lang'] == 'in']
data

,tweet_id,date,username,text,likes,retweets,replies,keyword,lang
0,2.040570e+18,Sat Apr 04 23:08:49 +0000 2026,shrimpingbae,sumpah kalo sampe itu anggota TNI ga dikasih s...,0,0,0,mati aja lo,in
1,2.041010e+18,Mon Apr 06 04:20:32 +0000 2026,xeyobog202,Gada tuh cerita pamer-pamer kekayaan di sini. ...,0,0,0,mati aja lo,in
2,2.041160e+18,Mon Apr 06 14:24:28 +0000 2026,LusyBule88,@tham878 Emaklo goblok idiot..termul...mati aj...,0,0,0,mati aja lo,in
3,2.040650e+18,Sun Apr 05 04:47:42 +0000 2026,DhiekaSetyawan,"@phamsaurus @AmirahWahdi Lah ada yg jawabin, g...",0,0,0,mati aja lo,in
4,2.039540e+18,Thu Apr 02 03:04:33 +0000 2026,sleepycatzzz_,Gimanapun baiknya lo kalau orang emang ga sene...,0,0,0,mati aja lo,in
...,...,...,...,...,...,...,...,...,...
27627,2.053630e+18,Mon May 11 00:18:59 +0000 2026,P3gEl,Ironisnya SPPG tersebut masih dalam proses pem...,0,0,0,lgbt penyakit,in
27628,2.053630e+18,Mon May 11 00:11:39 +0000 2026,ihanmujaer,aku... gemeter... plis... cantik... banget... ...,0,0,0,lgbt penyakit,in
27629,2.053520e+18,Sun May 10 16:54:30 +0000 2026,ladanghoki,🔞 pokoknya nentto wlw menghadapi hari senin ht...,15,3,1,lgbt penyakit,in
27630,2.051660e+18,Tue May 05 13:43:00 +0000 2026,paakminju,ᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ...,0,0,0,lgbt penyakit,in
27631,2.051660e+18,Tue May 05 13:42:40 +0000 2026,paakminju,ᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ...,1,1,0,lgbt penyakit,in

In [83]:
keyword = ['anjing', 'babi', 'monyet', 'kontol', 'ngentot', 'bangsat', 'jelek', 'goblok', 'tolol', 'cupu', 'bego', 'otak udang', 'dongo', 'mati aja', 'bajingan', 'ngaceng', 'lgbt']

In [ ]:
#GROUPING KEYWORDS WHICH HAVE THE SAME MEANINGS

def grouping_keyword(text):
    for word in keyword:
        if word in text:
            return word
    return text

data['keyword_group'] = data['keyword'].apply(grouping_keyword)

data['keyword_group'].value_counts()

keyword_group
anjing                1769
tolol                 1691
jelek                 1443
mati aja              1442
bangsat               1439
ngentot               1411
kontol                1318
babi                  1217
goblok                1148
bajingan              1141
monyet                1063
otak udang            1035
ngaceng               1017
bego                   986
dongo                  959
cupu                   910
ngewe                  830
lgbt                   504
kafir lang:id          376
'punya otak'           343
colmek                 326
jilmek                 297
memek                  252
dìentot                246
entot                  236
tobrut                 189
sange                  180
coli                   146
gendut item            109
toket                  103
"nyusahin ga guna"       2
Name: count, dtype: int64

In [85]:
data = data[['text']]
display(data)

                                                    text
0      sumpah kalo sampe itu anggota TNI ga dikasih s...
1      Gada tuh cerita pamer-pamer kekayaan di sini. ...
2      @tham878 Emaklo goblok idiot..termul...mati aj...
3      @phamsaurus @AmirahWahdi Lah ada yg jawabin, g...
4      Gimanapun baiknya lo kalau orang emang ga sene...
...                                                  ...
27627  Ironisnya SPPG tersebut masih dalam proses pem...
27628  aku... gemeter... plis... cantik... banget... ...
27629  🔞 pokoknya nentto wlw menghadapi hari senin ht...
27630  ᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ...
27631  ᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ...

[24128 rows x 1 columns]

In [ ]:
# CLEANING TEXT

def clean_text(text):
    text = re.sub(r'@\w+', 'USER', text) #replace the @ with USER token
    text = re.sub(r"http\S+|www\S+", "", text)
    text = re.sub(r"#\w+", "", text)
    text = re.sub(r"\brt\b", "", text)
    text = re.sub(r"\d+", "", text)
    text = re.sub(r"[^\w\s]", " ", text)
    text = re.sub(r'[\n\r\t]+', ' ', text)
    text = re.sub(r"(\w+)\^2", r"\1 \1", text)
    text = re.sub(r'\s+', ' ', text).strip()
    text = re.sub(r'[\u1160\u3164]', '', text)
    
    return text.strip()

In [87]:
# Remove Emoji Function
def remove_emoji(text):
    return emoji.replace_emoji(text, replace='')

In [ ]:
# Preserve intentional uppercase words and normalize other capitalization
def smart_case(text):
    words = text.split()
    result = []
    for word in words:
        if word == 'USER' or word == '[URL]':
            result.append(word)
        elif len(word) >= 2 and word.isupper():
            result.append(word)
        else:
            result.append(word.lower())
    return ' '.join(result)

In [89]:
def preprocess(text):

    text = clean_text(text)
    text = remove_emoji(text)
    text = smart_case(text)

    return text

In [90]:
data2 = data.copy()

In [91]:
data2['cleaned_text'] = data2['text'].apply(preprocess)

In [ ]:
# Data Before and After Cleaned
data2

,text,cleaned_text
0,sumpah kalo sampe itu anggota TNI ga dikasih s...,sumpah kalo sampe itu anggota TNI ga dikasih s...
1,Gada tuh cerita pamer-pamer kekayaan di sini. ...,gada tuh cerita pamer pamer kekayaan di sini m...
2,@tham878 Emaklo goblok idiot..termul...mati aj...,USER emaklo goblok idiot termul mati aja lo
3,"@phamsaurus @AmirahWahdi Lah ada yg jawabin, g...",USER USER lah ada yg jawabin gw jawabin lagi t...
4,Gimanapun baiknya lo kalau orang emang ga sene...,gimanapun baiknya lo kalau orang emang ga sene...
...,...,...
27627,Ironisnya SPPG tersebut masih dalam proses pem...,ironisnya SPPG tersebut masih dalam proses pem...
27628,aku... gemeter... plis... cantik... banget... ...,aku gemeter plis cantik banget ini kalo aku ov...
27629,🔞 pokoknya nentto wlw menghadapi hari senin ht...,pokoknya nentto wlw menghadapi hari senin
27630,ᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ...,pembersihan tl
27631,ᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ...,pembersihan tl

In [ ]:
# Check Missing Values
data2.isna().sum()

text            0
cleaned_text    0
dtype: int64

In [94]:
data = data2[["cleaned_text"]]

In [ ]:
# Check Duplicates
print(data["cleaned_text"].duplicated().sum())

515

In [ ]:
# Remove Duplicates
data = data.drop_duplicates(subset=['cleaned_text'])

In [99]:
print(data["cleaned_text"].duplicated().sum())

0