In [1]:
import pandas as pd
import numpy as np
import re
import emoji

In [2]:
# Read data
data = pd.read_csv(r"C:\Users\PC\ScraperTwitter\data\tweets.csv")
data

,tweet_id,date,username,text,likes,retweets,replies,keyword,lang
0,2.040570e+18,Sat Apr 04 23:08:49 +0000 2026,shrimpingbae,sumpah kalo sampe itu anggota TNI ga dikasih s...,0,0,0,mati aja lo,in
1,2.041010e+18,Mon Apr 06 04:20:32 +0000 2026,xeyobog202,Gada tuh cerita pamer-pamer kekayaan di sini. ...,0,0,0,mati aja lo,in
2,2.041160e+18,Mon Apr 06 14:24:28 +0000 2026,LusyBule88,@tham878 Emaklo goblok idiot..termul...mati aj...,0,0,0,mati aja lo,in
3,2.040650e+18,Sun Apr 05 04:47:42 +0000 2026,DhiekaSetyawan,"@phamsaurus @AmirahWahdi Lah ada yg jawabin, g...",0,0,0,mati aja lo,in
4,2.039540e+18,Thu Apr 02 03:04:33 +0000 2026,sleepycatzzz_,Gimanapun baiknya lo kalau orang emang ga sene...,0,0,0,mati aja lo,in
...,...,...,...,...,...,...,...,...,...
27628,2.053630e+18,Mon May 11 00:11:39 +0000 2026,ihanmujaer,aku... gemeter... plis... cantik... banget... ...,0,0,0,lgbt penyakit,in
27629,2.053520e+18,Sun May 10 16:54:30 +0000 2026,ladanghoki,🔞 pokoknya nentto wlw menghadapi hari senin ht...,15,3,1,lgbt penyakit,in
27630,2.051660e+18,Tue May 05 13:43:00 +0000 2026,paakminju,ᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ...,0,0,0,lgbt penyakit,in
27631,2.051660e+18,Tue May 05 13:42:40 +0000 2026,paakminju,ᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ...,1,1,0,lgbt penyakit,in
27632,2.053630e+18,Mon May 11 00:01:06 +0000 2026,KentaKanataa,BENTAR LG TAHUN AJARAN BARU AJDNDNCNCNFJJF,1,0,0,lgbt penyakit,NaN

In [3]:
print(data.duplicated().sum())

0

In [4]:
# Check Keyword Counts
data['keyword'].value_counts()

keyword
'anjing lu'                                 1157
kontol                                      1114
ngentot                                     1087
bangsat lu                                   997
ngewe                                        964
                                            ...
kontol since:2025-09-30 until:2025-11-30     135
"gendut jelek"                               130
"jawa goblok"                                 67
jelek gendut                                  12
"nyusahin ga guna"                             2
Name: count, Length: 61, dtype: int64

In [5]:
keyword = ['anjing', 'babi', 'monyet', 'kontol', 'ngentot', 'bangsat', 'jelek', 'goblok', 'tolol', 'cupu', 'bego', 'otak udang', 'dongo', 'mati aja', 'bajingan', 'ngaceng', 'lgbt']

In [6]:
# Grouping keywords which have the same meaning
def grouping_keyword(text):
    for word in keyword:
        if word in text:
            return word
    return text

data['keyword_group'] = data['keyword'].apply(grouping_keyword)

data['keyword_group'].value_counts()

keyword_group
tolol                 1909
anjing                1896
ngentot               1641
mati aja              1611
jelek                 1554
bangsat               1509
babi                  1469
kontol                1435
goblok                1286
bajingan              1197
bego                  1184
monyet                1169
cupu                  1155
otak udang            1098
ngaceng               1083
dongo                 1059
ngewe                  964
lgbt                   655
colmek                 534
coli                   389
kafir lang:id          380
'punya otak'           354
memek                  342
jilmek                 326
dìentot                286
entot                  267
sange                  262
tobrut                 237
toket                  214
gendut item            166
"nyusahin ga guna"       2
Name: count, dtype: int64

In [7]:
# Count how many keywords are there
data['keyword_group'].nunique()

31

In [8]:
# Filtering Indonesian tweets
data = data[data['lang'] == 'in']
data

,tweet_id,date,username,text,likes,retweets,replies,keyword,lang,keyword_group
0,2.040570e+18,Sat Apr 04 23:08:49 +0000 2026,shrimpingbae,sumpah kalo sampe itu anggota TNI ga dikasih s...,0,0,0,mati aja lo,in,mati aja
1,2.041010e+18,Mon Apr 06 04:20:32 +0000 2026,xeyobog202,Gada tuh cerita pamer-pamer kekayaan di sini. ...,0,0,0,mati aja lo,in,mati aja
2,2.041160e+18,Mon Apr 06 14:24:28 +0000 2026,LusyBule88,@tham878 Emaklo goblok idiot..termul...mati aj...,0,0,0,mati aja lo,in,mati aja
3,2.040650e+18,Sun Apr 05 04:47:42 +0000 2026,DhiekaSetyawan,"@phamsaurus @AmirahWahdi Lah ada yg jawabin, g...",0,0,0,mati aja lo,in,mati aja
4,2.039540e+18,Thu Apr 02 03:04:33 +0000 2026,sleepycatzzz_,Gimanapun baiknya lo kalau orang emang ga sene...,0,0,0,mati aja lo,in,mati aja
...,...,...,...,...,...,...,...,...,...,...
27627,2.053630e+18,Mon May 11 00:18:59 +0000 2026,P3gEl,Ironisnya SPPG tersebut masih dalam proses pem...,0,0,0,lgbt penyakit,in,lgbt
27628,2.053630e+18,Mon May 11 00:11:39 +0000 2026,ihanmujaer,aku... gemeter... plis... cantik... banget... ...,0,0,0,lgbt penyakit,in,lgbt
27629,2.053520e+18,Sun May 10 16:54:30 +0000 2026,ladanghoki,🔞 pokoknya nentto wlw menghadapi hari senin ht...,15,3,1,lgbt penyakit,in,lgbt
27630,2.051660e+18,Tue May 05 13:43:00 +0000 2026,paakminju,ᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ...,0,0,0,lgbt penyakit,in,lgbt
27631,2.051660e+18,Tue May 05 13:42:40 +0000 2026,paakminju,ᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ...,1,1,0,lgbt penyakit,in,lgbt

In [9]:
# Cleaning Text Function

def clean_text(text):
    text = re.sub(r'@\w+', '', text)
    text = re.sub(r"http\S+|www\S+", "", text)
    text = re.sub(r"#\w+", "", text)
    text = re.sub(r"\brt\b", "", text)
    text = re.sub(r"\d+", "", text)
    text = re.sub(r"[^\w\s]", " ", text)
    text = re.sub(r'[\n\r\t]+', ' ', text)
    text = re.sub(r"(\w+)\^2", r"\1 \1", text)
    text = re.sub(r'\s+', ' ', text).strip()
    text = re.sub(r'[\u1160\u3164]', '', text)
    text = re.sub(r'USER', '', text)

    return text.strip()

In [10]:
# Remove Emoji Function
def remove_emoji(text):
    return emoji.replace_emoji(text, replace='')

In [11]:
# Preserve intentional uppercase words and normalize other capitalization

def smart_case(text):
    words = text.split()
    result = []
    for word in words:
        if word == 'USER' or word == '[URL]':
            result.append(word)
        elif len(word) >= 2 and word.isupper():
            result.append(word)
        else:
            result.append(word.lower())
    return ' '.join(result)

In [12]:
def preprocess(text):

    text = clean_text(text)
    text = remove_emoji(text)
    text = smart_case(text)

    return text

In [13]:
# Apply Cleaning Text
data['cleaned_text'] = data['text'].apply(preprocess)

In [14]:
# Remove Strange Symbols
data['cleaned_text'] = data['cleaned_text'].replace(r'^\s*$', np.nan, regex=True)

In [15]:
data

,tweet_id,date,username,text,likes,retweets,replies,keyword,lang,keyword_group,cleaned_text
0,2.040570e+18,Sat Apr 04 23:08:49 +0000 2026,shrimpingbae,sumpah kalo sampe itu anggota TNI ga dikasih s...,0,0,0,mati aja lo,in,mati aja,sumpah kalo sampe itu anggota TNI ga dikasih s...
1,2.041010e+18,Mon Apr 06 04:20:32 +0000 2026,xeyobog202,Gada tuh cerita pamer-pamer kekayaan di sini. ...,0,0,0,mati aja lo,in,mati aja,gada tuh cerita pamer pamer kekayaan di sini m...
2,2.041160e+18,Mon Apr 06 14:24:28 +0000 2026,LusyBule88,@tham878 Emaklo goblok idiot..termul...mati aj...,0,0,0,mati aja lo,in,mati aja,emaklo goblok idiot termul mati aja lo
3,2.040650e+18,Sun Apr 05 04:47:42 +0000 2026,DhiekaSetyawan,"@phamsaurus @AmirahWahdi Lah ada yg jawabin, g...",0,0,0,mati aja lo,in,mati aja,lah ada yg jawabin gw jawabin lagi trus hrs gm...
4,2.039540e+18,Thu Apr 02 03:04:33 +0000 2026,sleepycatzzz_,Gimanapun baiknya lo kalau orang emang ga sene...,0,0,0,mati aja lo,in,mati aja,gimanapun baiknya lo kalau orang emang ga sene...
...,...,...,...,...,...,...,...,...,...,...,...
27627,2.053630e+18,Mon May 11 00:18:59 +0000 2026,P3gEl,Ironisnya SPPG tersebut masih dalam proses pem...,0,0,0,lgbt penyakit,in,lgbt,ironisnya SPPG tersebut masih dalam proses pem...
27628,2.053630e+18,Mon May 11 00:11:39 +0000 2026,ihanmujaer,aku... gemeter... plis... cantik... banget... ...,0,0,0,lgbt penyakit,in,lgbt,aku gemeter plis cantik banget ini kalo aku ov...
27629,2.053520e+18,Sun May 10 16:54:30 +0000 2026,ladanghoki,🔞 pokoknya nentto wlw menghadapi hari senin ht...,15,3,1,lgbt penyakit,in,lgbt,pokoknya nentto wlw menghadapi hari senin
27630,2.051660e+18,Tue May 05 13:43:00 +0000 2026,paakminju,ᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ...,0,0,0,lgbt penyakit,in,lgbt,pembersihan tl
27631,2.051660e+18,Tue May 05 13:42:40 +0000 2026,paakminju,ᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ...,1,1,0,lgbt penyakit,in,lgbt,pembersihan tl

In [16]:
# Check Missing Values
print(data.isna().sum())

tweet_id         0
date             0
username         0
text             0
likes            0
retweets         0
replies          0
keyword          0
lang             0
keyword_group    0
cleaned_text     1
dtype: int64

In [17]:
data.to_excel('cleaned.xlsx', index=False)

In [18]:
ex = pd.read_excel(r"C:\Users\PC\ScraperTwitter\data\cleaned.xlsx")
ex

,tweet_id,date,username,text,likes,retweets,replies,keyword,lang,keyword_group,cleaned_text
0,2040570000000000000,Sat Apr 04 23:08:49 +0000 2026,shrimpingbae,sumpah kalo sampe itu anggota TNI ga dikasih s...,0,0,0,mati aja lo,in,mati aja,sumpah kalo sampe itu anggota TNI ga dikasih s...
1,2041010000000000000,Mon Apr 06 04:20:32 +0000 2026,xeyobog202,Gada tuh cerita pamer-pamer kekayaan di sini. ...,0,0,0,mati aja lo,in,mati aja,gada tuh cerita pamer pamer kekayaan di sini m...
2,2041160000000000000,Mon Apr 06 14:24:28 +0000 2026,LusyBule88,@tham878 Emaklo goblok idiot..termul...mati aj...,0,0,0,mati aja lo,in,mati aja,emaklo goblok idiot termul mati aja lo
3,2040650000000000000,Sun Apr 05 04:47:42 +0000 2026,DhiekaSetyawan,"@phamsaurus @AmirahWahdi Lah ada yg jawabin, g...",0,0,0,mati aja lo,in,mati aja,lah ada yg jawabin gw jawabin lagi trus hrs gm...
4,2039540000000000000,Thu Apr 02 03:04:33 +0000 2026,sleepycatzzz_,Gimanapun baiknya lo kalau orang emang ga sene...,0,0,0,mati aja lo,in,mati aja,gimanapun baiknya lo kalau orang emang ga sene...
...,...,...,...,...,...,...,...,...,...,...,...
24123,2053630000000000000,Mon May 11 00:18:59 +0000 2026,P3gEl,Ironisnya SPPG tersebut masih dalam proses pem...,0,0,0,lgbt penyakit,in,lgbt,ironisnya SPPG tersebut masih dalam proses pem...
24124,2053630000000000000,Mon May 11 00:11:39 +0000 2026,ihanmujaer,aku... gemeter... plis... cantik... banget... ...,0,0,0,lgbt penyakit,in,lgbt,aku gemeter plis cantik banget ini kalo aku ov...
24125,2053520000000000000,Sun May 10 16:54:30 +0000 2026,ladanghoki,🔞 pokoknya nentto wlw menghadapi hari senin ht...,15,3,1,lgbt penyakit,in,lgbt,pokoknya nentto wlw menghadapi hari senin
24126,2051660000000000000,Tue May 05 13:43:00 +0000 2026,paakminju,ᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ...,0,0,0,lgbt penyakit,in,lgbt,pembersihan tl
24127,2051660000000000000,Tue May 05 13:42:40 +0000 2026,paakminju,ᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ\r\n\r\nᅠ...,1,1,0,lgbt penyakit,in,lgbt,pembersihan tl

In [19]:
# Filtering Column
ex = ex[["cleaned_text"]]
ex

                                            cleaned_text
0      sumpah kalo sampe itu anggota TNI ga dikasih s...
1      gada tuh cerita pamer pamer kekayaan di sini m...
2                 emaklo goblok idiot termul mati aja lo
3      lah ada yg jawabin gw jawabin lagi trus hrs gm...
4      gimanapun baiknya lo kalau orang emang ga sene...
...                                                  ...
24123  ironisnya SPPG tersebut masih dalam proses pem...
24124  aku gemeter plis cantik banget ini kalo aku ov...
24125          pokoknya nentto wlw menghadapi hari senin
24126                                     pembersihan tl
24127                                     pembersihan tl

[24128 rows x 1 columns]

In [24]:
# Check Duplicates
print(ex["cleaned_text"].duplicated().sum())

610

In [25]:
# Remove Duplicates
ex = ex.drop_duplicates(subset=['cleaned_text'])

In [20]:
ex.to_excel('text.xlsx', index=False)

# Prepare The Data Before Vertex

In [21]:
ex.to_json("cleaned.json", orient="records", force_ascii=False, indent=4)

In [22]:
import json

with open('cleaned.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

with open('input_vertex.jsonl', 'w', encoding='utf-8') as f:
    for item in data:
        tweet = item['cleaned_text']
        structure = {
            "contents": [
                {
                    "role": "user",
                    "parts": [{"text": tweet}]
                }
            ]
        }
        f.write(json.dumps(structure, ensure_ascii=False) + '\n')

print("Selesai! File input_vertex.jsonl sudah siap.")

Selesai! File input_vertex.jsonl sudah siap.

In [23]:
# Insert prompt into the JSONL data

file_input_lama = "input_vertex.jsonl"  
file_output_vertex = "vertex.jsonl"

PROMPT_TEMPLATE = """Kamu adalah seorang ahli analisis teks dan moderator media sosial Indonesia. Tugasmu adalah mengklasifikasikan tweet ke dalam salah satu dari 5 kategori berdasarkan definisi berikut.

**PENTING:** Sebuah tweet HANYA bisa dikategorikan sebagai salah satu tipe Cyberbullying jika terdapat TARGET yang jelas di dalam teks seperti penyebutan USER maupun individu atau kelompok yang diserang/dituju. Jika tidak ada target spesifik, masukkan ke "Non-Cyberbullying".

KATEGORI DAN DEFINISI:
1. "Hate Speech" -> Ujaran secara publik yang mengekspresikan kebencian atau kekerasan terhadap seseorang maupun suatu kelompok berdasarkan ras, agama, jenis kelamin, atau orientasi seksual.
2. "Sexual Harassment" -> Teks atau pesan yang bersifat melecehkan secara seksual, atau merujuk pada aktivitas/foto seksual yang menyudutkan target.
3. "Kata Kasar dan Vulgar" -> Memberi pesan dengan kata-kata kasar, kotor, makian, atau bahasa vulgar yang menyerang dan dapat menyinggung orang lain.
4. "Body Shaming" -> Merundung penampilan fisik seseorang. Merupakan bentuk kekerasan verbal-emosional yang tujuannya beragam, mulai dari bahan candaan, memperkeruh suasana, hingga menghina target.
5. "Non-Cyberbullying" -> Tweet yang berupa opini kritis, keluhan umum, ekspresi emosi/kata kasar tanpa target personal, atau teks netral/positif.

ATURAN OUTPUT:
Berikan output HANYA dalam format JSON mentah dengan key "label" dan "alasan" singkat yang mendasari keputusanmu. Jangan berikan teks pengantar atau penutup apa pun selain JSON tersebut.

Tweet yang harus dinilai:
"{tweet_text}" """

# 3. Proses konversi data
print("Memulai konversi struktur JSONL...")
counter = 0

with open(file_input_lama, 'r', encoding='utf-8') as infile, \
     open(file_output_vertex, 'w', encoding='utf-8') as outfile:
    
    for line in infile:
        if not line.strip():
            continue
            
        data_lama = json.loads(line)
        tweet_asli = data_lama["contents"][0]["parts"][0]["text"]
        
        prompt_lengkap = PROMPT_TEMPLATE.format(tweet_text=tweet_asli)
        
        # Susun ulang untuk Vertex AI
        struktur_baru = {
            "request": {
                "contents": [
                    {
                        "role": "user",
                        "parts": [
                            {
                                "text": prompt_lengkap
                            }
                        ]
                    }
                ]
            }
        }
        
        outfile.write(json.dumps(struktur_baru, ensure_ascii=False) + '\n')
        counter += 1

print(f"Selesai! Berhasil memproses {counter} data tweet ke file baru: {file_output_vertex}")

Memulai konversi struktur JSONL...
Selesai! Berhasil memproses 24128 data tweet ke file baru: vertex.jsonl